const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { pathToFileURL } = require('node:url');
const root = path.resolve(__dirname,'..');
const out = __dirname;
const url = pathToFileURL(path.join(root,'01_海岛探险教案.html')).href;
const observations = {stations:[],reports:[],screens:[],checks:[],errors:[],externalRequests:[]};
let browser;
async function forceImages(page,selector){
 await page.locator(selector+' img').evaluateAll(images=>images.forEach(img=>img.loading='eager'));
 await page.waitForFunction(s=>[...document.querySelectorAll(s+' img')].every(img=>img.complete&&img.naturalWidth>0),selector);
}
async function open(page,id){
 await page.evaluate(id=>document.querySelector('.station-node[data-station="'+id+'"]').click(),id);
 await page.waitForFunction(id=>location.hash==='#station/'+id&&document.querySelector('#lesson-dialog').open,id);
}
(async()=>{
 browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},offline:true});
 context.on('page',p=>{
   p.on('pageerror',e=>observations.errors.push(e.message));
   p.on('request',r=>{if(/^https?:/.test(r.url())) observations.externalRequests.push(r.url());});
 });
 const page=await context.newPage();
 await page.goto(url,{waitUntil:'load'});
 assert.equal(await page.locator('.station-node').count(),16);
 assert.equal(await page.locator('.station-card').count(),16);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:path.join(out,'home.png')});
 await page.locator('.atlas-section').screenshot({path:path.join(out,'map.png')});
 await page.locator('#show-routes').check();
 assert.ok(await page.locator('.world-map').evaluate(el=>el.classList.contains('show-routes')));
 await page.locator('.atlas-section').screenshot({path:path.join(out,'data_routes.png')});
 await page.locator('#show-routes').uncheck();
 const ids=await page.evaluate(()=>window.LESSONS.map(s=>s.id));
 for(const id of ids){
   await open(page,id);
   assert.equal(await page.locator('#lesson-content .quiz').count(),1);
   assert.ok(await page.locator('#lesson-content h2').count()>=4);
   await forceImages(page,'#lesson-content');
   const facts=await page.locator('#lesson-content').evaluate(el=>({text:el.innerText.length,figures:el.querySelectorAll('.real-figure').length,unexpanded:el.textContent.includes('{{'),overflow:el.scrollWidth>el.clientWidth+1}));
   assert.equal(await page.locator('#lesson-content .figure-reading details').count(),0,'figure guides must stay expanded');
   const guides=await page.locator('#lesson-content .guide-section').count();
   const illustrations=await page.locator('#lesson-content .teaching-visual').count();
   facts.guides=guides;facts.illustrations=illustrations;
   assert.equal(facts.unexpanded,false);
   assert.equal(facts.overflow,false,id+' content overflow');
   observations.stations.push({id,...facts});
 }
 observations.checks.push('16 个站点、23 张图全部离线打开');
 await open(page,'de');
 assert.equal(await page.locator('#up-count').textContent(),'1,087');
 assert.equal(await page.locator('#down-count').textContent(),'826');
 assert.equal(await page.locator('#ns-count').textContent(),'13,399');
 assert.ok((await page.locator('#gene-answer').textContent()).includes('未达到候选阈值'));
 await page.locator('#fdr').selectOption('0.01');
 assert.ok(Number((await page.locator('#up-count').textContent()).replaceAll(',',''))<=1087);
 await page.locator('#reset-threshold').click();
 assert.equal(await page.locator('#up-count').textContent(),'1,087');
 await page.locator('#gene-query').fill('AT1G13930');
 assert.ok((await page.locator('#gene-answer').textContent()).includes('上调候选'));
 await page.locator('#gene-query').fill('UNKNOWN_GENE');
 assert.ok((await page.locator('#gene-answer').textContent()).includes('没有找到'));
 await page.locator('#swap-direction').click();
 assert.equal(await page.locator('#direction-value').textContent(),'−2');
 const answer=await page.evaluate(()=>window.LESSONS.find(s=>s.id==='de').quiz.answer);
 await page.locator(`#lesson-content .quiz input[value="${answer}"]`).check();
 await page.locator('[data-check-answer]').click();
 assert.ok((await page.locator('.quiz-feedback').textContent()).includes('答对'));
 await page.locator('#mark-read').click();
 await page.reload({waitUntil:'load'});
 assert.equal(await page.locator('#lesson-dialog').evaluate(el=>el.open),true);
 assert.equal(await page.locator('#mark-read').getAttribute('aria-pressed'),'true');
 assert.ok((await page.locator('#progress-label').textContent()).includes('1 / 16'));
 observations.checks.push('真实阈值计数、基因查询、方向交换、自测解析、刷新恢复进度');
 await page.locator('#lesson-fullscreen').click();
 assert.ok(await page.locator('#lesson-dialog').evaluate(el=>el.clientWidth===innerWidth));
 await page.screenshot({path:path.join(out,'lecture.png')});
 await page.locator('#lesson-fullscreen').click();
 await open(page,'matrix');
 await page.locator('#other-rna').evaluate(el=>{el.value='450';el.dispatchEvent(new Event('input',{bubbles:true}));});
 assert.equal(await page.locator('#composition-output').textContent(),'10.0%');
 await open(page,'gsea');
 await page.locator('#shuffle-rank').click();
 assert.ok((await page.locator('#rank-explanation').textContent()).includes('分布在整条队伍'));
 await open(page,'plots');
 await forceImages(page,'#lesson-content');
 await page.locator('[data-annotations]').first().click();
 assert.equal(await page.locator('.real-figure').first().locator('.figure-marker').first().isVisible(),false);
 await page.locator('[data-annotations]').first().click();
 await page.locator('.real-figure [data-zoom]').first().click();
 await forceImages(page,'#image-scroll');
 assert.equal(await page.locator('#image-dialog').evaluate(el=>el.open),true);
 await page.locator('#image-original').click();
 assert.ok(await page.locator('#image-scroll').evaluate(el=>el.classList.contains('original-size')));
 await page.locator('#image-fit').click();
 await page.screenshot({path:path.join(out,'figure.png')});
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('#image-dialog').evaluate(el=>el.open),false);
 assert.equal(await page.locator('#lesson-dialog').evaluate(el=>el.open),true);
 await page.locator('#lesson-glossary').click();
 await page.locator('#glossary-query').fill('TPM');
 assert.ok((await page.locator('#glossary-entries').textContent()).includes('样本'));
 await page.keyboard.press('Escape');
 await page.waitForFunction(()=>!document.getElementById('glossary-dialog').open);
 assert.equal(await page.locator('#lesson-dialog').evaluate(el=>el.open),true);
 await page.keyboard.press('Tab');
 assert.equal(await page.evaluate(()=>document.activeElement.closest('#lesson-dialog')!==null),true);
 await page.locator('#close-lesson').click();
 assert.equal(await page.locator('#lesson-dialog').evaluate(el=>el.open),false);
 observations.checks.push('课程全屏、组成与排序实验、图片标注、嵌套窗口 Esc 与键盘焦点');
 await page.locator('#list-view').click();
 assert.equal(await page.locator('#station-list').isVisible(),true);
 assert.equal(await page.locator('.map-scroller').isVisible(),false);
 await page.locator('#map-view').click();
 const reports=['case/2data/rawdata/qc/ZT4_rep_1_1_fastqc.html','case/2data/cleandata/qc/ZT4_rep_1_clean_1_fastqc.html','case/2data/cleandata/fastp/ZT4_rep_1.fp.html'];
 const reportPage=await context.newPage();
 for(const report of reports){
   await reportPage.goto(pathToFileURL(path.join(root,report)).href,{waitUntil:'load'});
   if(report.includes('.fp.')){
     await reportPage.waitForFunction(()=>document.querySelectorAll('.js-plotly-plot').length>0);
     assert.ok(await reportPage.locator('.js-plotly-plot').count()>3);
     await reportPage.screenshot({path:path.join(out,'fastp_offline.png')});
   }else{
     await forceImages(reportPage,'body');
   }
   observations.reports.push({report,offline:true});
 }
 await reportPage.goto(pathToFileURL(path.join(root,'library/脚本与资料目录.html')).href,{waitUntil:'load'});
 assert.equal(await reportPage.locator('.library-list li').count(),90);
 await reportPage.getByRole('link',{name:'12 火山图',exact:true}).click();
 assert.ok(await reportPage.locator('pre').count()>0);
 assert.ok(await reportPage.locator('a[href$="12_volcano.R.html"]').count()>0);
 await reportPage.locator('a[href$="12_volcano.R.html"]').first().click();
 assert.ok((await reportPage.locator('.source-code').textContent()).includes('EnhancedVolcano')); 
 await forceImages(reportPage,'body');
 observations.checks.push('FastQC 与 fastp 原报告离线绘图、本地 MD 网页及原文下载入口');
 for(const [width,height] of [[390,844],[768,1024],[1920,1080]]){
   await page.setViewportSize({width,height});
   await page.goto(url,{waitUntil:'load'});
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'page overflow '+width);
   await page.screenshot({path:path.join(out,`home_${width}.png`)});
   await open(page,'qc');
   await forceImages(page,'#lesson-content');
   assert.equal(await page.locator('#lesson-content').evaluate(el=>el.scrollWidth<=el.clientWidth+1),true,'lesson overflow '+width);
   assert.ok(await page.locator('#lesson-dialog').evaluate(el=>el.getBoundingClientRect().right<=innerWidth+1));
   await page.screenshot({path:path.join(out,`lesson_${width}.png`)});
   observations.screens.push({width,height,pass:true});
 }
 await page.locator('#close-lesson').click();
 await context.close();
 const noJS=await browser.newContext({javaScriptEnabled:false,offline:true,viewport:{width:1100,height:900}});
 const staticPage=await noJS.newPage();
 await staticPage.goto(pathToFileURL(path.join(root,'02_完整教案_阅读与打印.html')).href,{waitUntil:'load'});
 assert.equal(await staticPage.locator('.print-lesson').count(),16);
 assert.equal(await staticPage.locator('.quiz details[open]').count(),16);
 await staticPage.emulateMedia({media:'print'});
 assert.equal(await staticPage.locator('.quiz details p').first().isVisible(),true);
 await noJS.close();
 observations.checks.push('禁用 JavaScript 时全文可读，打印自测解析可见');
 const moved=fs.mkdtempSync(path.join(os.tmpdir(),'rnaseq-teaching-relocation-'));
 const movedRoot=path.join(moved,'移动 后的教案');
 fs.cpSync(root,movedRoot,{recursive:true,filter:p=>!p.startsWith(path.join(root,'qa'))});
 const movedContext=await browser.newContext({offline:true,viewport:{width:1280,height:900}});
 const movedPage=await movedContext.newPage();
 await movedPage.goto(pathToFileURL(path.join(movedRoot,'01_海岛探险教案.html')).href,{waitUntil:'load'});
 await open(movedPage,'filter');
 await forceImages(movedPage,'#lesson-content');
 assert.equal(await movedPage.locator('#lesson-content .real-figure').count(),3);
 await movedPage.goto(pathToFileURL(path.join(movedRoot,'library/脚本与资料目录.html')).href,{waitUntil:'load'});
 assert.equal(await movedPage.locator('.library-list li').count(),90);
 await movedContext.close();
 fs.rmSync(moved,{recursive:true,force:true});
 observations.checks.push('完整复制到含空格的新目录并改名后，课程、图片与资料馆可读');
 assert.deepEqual(observations.errors,[]);
 assert.deepEqual(observations.externalRequests,[]);
 observations.pass=true;
 fs.writeFileSync(path.join(out,'browser_validation.json'),JSON.stringify(observations,null,2));
 console.log(JSON.stringify({pass:true,stations:observations.stations.length,reports:observations.reports.length,screens:observations.screens,checks:observations.checks,errors:observations.errors,externalRequests:observations.externalRequests}));
 await browser.close();
})().catch(async error=>{
 observations.pass=false;observations.failure=error.stack;
 fs.writeFileSync(path.join(out,'browser_validation.json'),JSON.stringify(observations,null,2));
 console.error(error);
 if(browser)await browser.close();
 process.exit(1);
});
